import { BentoTokens } from "./bentoTokens";

const remBaseSize = 16;
const pixelToRem = (px: number) => `${px / remBaseSize}rem`;

const colors = {
  white: "#FFFFFF",
  white_80: "rgba(255, 255, 255, 0.8)",
  black: "#000000",
  black_16: "rgba(0, 0, 0, 0.16)",
  bentoViolet10: "#B3BEFF",
  bentoViolet20: "#7F77FF",
  bentoViolet40: "#5C17E5",
  neutral01: "#F6F8FB",
  neutral05: "#ECEFF4",
  neutral10: "#DEE4ED",
  neutral20: "#CBD4E1",
  neutral20_20: "rgba(203, 212, 225, 0.2)",
  neutral20_40: "rgba(203, 212, 225, 0.4)",
  neutral30: "#B6C2D3",
  neutral40: "#9AA8BC",
  neutral40_30: "rgba(154, 168, 188, 0.3)",
  neutral50: "#728197",
  neutral60: "#525E6F",
  neutral80: "#27313F",
  neutral90: "#1A212B",
  neutral90_60: "rgba(26, 33, 43, 0.6)",
  informative05: "#E0EDFF",
  informative30: "#5598F6",
  informative50: "#105FCE",
  positive05: "#E1FCDE",
  positive50: "#17BF33",
  positive70: "#016A1C",
  warning05: "#FFF2D2",
  warning40: "#F2930D",
  warning60: "#BA5900",
  negative05: "#FFD4D8",
  negative30: "#F14A58",
  negative40: "#E42131",
  negative40_10: "rgba(228, 33, 49, 0.1)",
  negative60: "#B1000F",
  interactive05: "#D0DCFF",
  interactive10: "#B3BEFF",
  interactive10_40: "rgba(179, 190, 255, 0.4)",
  interactive40: "#5C17E5",
  interactive60: "#360090",
  red01: "#FFF2F4",
  red10: "#FFBDCB",
  red30: "#FC5275",
  red50: "#D20E36",
  orange01: "#FFF6F2",
  orange10: "#FFD4BC",
  orange30: "#FB8951",
  orange50: "#D24E0D",
  yellow01: "#FFFCF2",
  yellow10: "#FFF4B2",
  yellow30: "#FFD439",
  yellow50: "#C39200",
  green01: "#F9FFF2",
  green10: "#DBF1BC",
  green30: "#A3D65C",
  green50: "#5F9F07",
  jade01: "#F2FFF8",
  jade10: "#B7F6D7",
  jade30: "#51E098",
  jade50: "#01A252",
  blue01: "#F2FCFF",
  blue10: "#BCF2FF",
  blue30: "#51D0FB",
  blue50: "#0DA0D2",
  indigo01: "#ECEFF4",
  indigo10: "#C0D3F9",
  indigo30: "#5F8CE6",
  indigo50: "#1D54C2",
  violet01: "#FAF2FF",
  violet10: "#DABEEA",
  violet30: "#A463C7",
  violet50: "#7C20AD",
  pink01: "#FFF2F9",
  pink10: "#F8B0DA",
  pink30: "#E648A4",
  pink50: "#C20B76",
};

const displayFontFamily = "Lexend, Arial, sans-serif";
const groteskFontFamily = "Lexend, Arial, sans-serif";

export const defaultTokens: BentoTokens = {
  typography: {
    body: {
      fontFamily: groteskFontFamily,
      fontWeight: { regular: "400", strong: "600" },
      sizes: {
        small: { fontSize: pixelToRem(12), lineHeight: pixelToRem(18) },
        medium: { fontSize: pixelToRem(14), lineHeight: pixelToRem(20) },
        large: { fontSize: pixelToRem(16), lineHeight: pixelToRem(24) },
      },
    },
    headline: {
      fontFamily: displayFontFamily,
      fontWeight: "600",
      sizes: {
        small: { fontSize: pixelToRem(32), lineHeight: pixelToRem(36) },
        medium: { fontSize: pixelToRem(36), lineHeight: pixelToRem(40) },
        large: { fontSize: pixelToRem(40), lineHeight: pixelToRem(44) },
      },
    },
    display: {
      fontFamily: displayFontFamily,
      fontWeight: "600",
      sizes: {
        small: { fontSize: pixelToRem(44), lineHeight: pixelToRem(50) },
        medium: { fontSize: pixelToRem(52), lineHeight: pixelToRem(58) },
        large: { fontSize: pixelToRem(64), lineHeight: pixelToRem(72) },
      },
    },
    label: {
      fontFamily: groteskFontFamily,
      fontWeight: "500",
      sizes: {
        small: { fontSize: pixelToRem(12), lineHeight: pixelToRem(18) },
        medium: { fontSize: pixelToRem(14), lineHeight: pixelToRem(20) },
        large: { fontSize: pixelToRem(16), lineHeight: pixelToRem(24) },
      },
    },
    title: {
      fontFamily: displayFontFamily,
      fontWeight: "600",
      sizes: {
        small: { fontSize: pixelToRem(14), lineHeight: pixelToRem(16) },
        medium: { fontSize: pixelToRem(16), lineHeight: pixelToRem(18) },
        large: { fontSize: pixelToRem(22), lineHeight: pixelToRem(24) },
      },
    },
  },
  brandColor: {
    brandPrimary: colors.bentoViolet40,
    brandSecondary: colors.bentoViolet20,
    brandTertiary: colors.bentoViolet10,
  },
  backgroundColor: {
    backgroundPrimary: colors.white,
    backgroundSecondary: colors.neutral01,
    backgroundOverlay: colors.neutral20_40,
    backgroundPrimaryInverse: colors.neutral90,
    backgroundSecondaryInverse: colors.neutral80,
    backgroundInteractive: colors.interactive40,
    backgroundInteractiveOverlay: colors.interactive10_40,
    backgroundInformative: colors.informative05,
    backgroundPositive: colors.positive05,
    backgroundWarning: colors.warning05,
    backgroundNegative: colors.negative05,
    backgroundLightScrim: colors.white_80,
    backgroundDarkScrim: colors.neutral90_60,
  },
  foregroundColor: {
    foregroundPrimary: colors.neutral90,
    foregroundSecondary: colors.neutral50,
    foregroundPrimaryInverse: colors.white,
    foregroundSecondaryInverse: colors.neutral30,
    foregroundInteractive: colors.interactive40,
    foregroundInformative: colors.informative30,
    foregroundPositive: colors.positive50,
    foregroundWarning: colors.warning40,
    foregroundNegative: colors.negative30,
    foregroundDisabled: colors.neutral40_30,
  },
  textColor: {
    textPrimary: colors.neutral90,
    textSecondary: colors.neutral50,
    textPrimaryInverse: colors.neutral01,
    textSecondaryInverse: colors.neutral30,
    textInteractive: colors.interactive40,
    textInformative: colors.informative50,
    textPositive: colors.positive70,
    textWarning: colors.warning60,
    textNegative: colors.negative60,
    textDisabled: colors.neutral40_30,
  },
  interactiveBackgroundColor: {
    primarySolidEnabledBackground: colors.interactive40,
    primarySolidHoverBackground: colors.interactive60,
    primarySolidFocusBackground: colors.interactive60,
    primaryTransparentEnabledBackground: "transparent",
    primaryTransparentHoverBackground: colors.interactive10_40,
    primaryTransparentFocusBackground: colors.interactive10_40,
    secondarySolidEnabledBackground: colors.neutral05,
    secondarySolidHoverBackground: colors.neutral20,
    secondarySolidFocusBackground: colors.neutral20,
    secondaryTransparentEnabledBackground: "transparent",
    secondaryTransparentHoverBackground: colors.neutral20_40,
    secondaryTransparentFocusBackground: colors.neutral20_40,
    dangerSolidEnabledBackground: colors.negative40,
    dangerSolidHoverBackground: colors.negative60,
    dangerSolidFocusBackground: colors.negative60,
    dangerTransparentEnabledBackground: "transparent",
    dangerTransparentHoverBackground: colors.negative40_10,
    dangerTransparentFocusBackground: colors.negative40_10,
    disabledSolidBackground: colors.neutral20_20,
    disabledTransparentBackground: "transparent",
  },
  interactiveForegroundColor: {
    primarySolidEnabledForeground: colors.white,
    primarySolidHoverForeground: colors.white,
    primarySolidFocusForeground: colors.white,
    primaryTransparentEnabledForeground: colors.interactive40,
    primaryTransparentHoverForeground: colors.interactive60,
    primaryTransparentFocusForeground: colors.interactive60,
    secondarySolidEnabledForeground: colors.neutral90,
    secondarySolidHoverForeground: colors.neutral90,
    secondarySolidFocusForeground: colors.neutral90,
    secondaryTransparentEnabledForeground: colors.neutral80,
    secondaryTransparentHoverForeground: colors.black,
    secondaryTransparentFocusForeground: colors.black,
    dangerSolidEnabledForeground: colors.white,
    dangerSolidHoverForeground: colors.white,
    dangerSolidFocusForeground: colors.white,
    dangerTransparentEnabledForeground: colors.negative40,
    dangerTransparentHoverForeground: colors.negative60,
    dangerTransparentFocusForeground: colors.negative60,
    disabledSolidForeground: colors.neutral40_30,
    disabledTransparentForeground: colors.neutral40_30,
    linkEnabled: colors.interactive40,
    linkHover: colors.interactive60,
    linkFocus: colors.interactive60,
    linkDisabled: colors.neutral40_30,
    linkEnabledInverse: colors.interactive10,
    linkHoverInverse: colors.interactive05,
    linkFocusInverse: colors.interactive05,
    linkDisabledInverse: colors.neutral60,
  },
  outlineColor: {
    outlineInteractive: colors.interactive40,
    outlineInteractivePrimaryEnabled: colors.interactive40,
    outlineInteractivePrimaryFocus: colors.interactive60,
    outlineInteractivePrimaryHover: colors.interactive60,
    outlineInteractiveSecondaryEnabled: colors.neutral80,
    outlineInteractiveSecondaryFocus: colors.black,
    outlineInteractiveSecondaryHover: colors.black,
    outlineInteractiveDangerEnabled: colors.negative40,
    outlineInteractiveDangerFocus: colors.negative60,
    outlineInteractiveDangerHover: colors.negative60,
    outlineInteractiveDisabled: colors.neutral40_30,
    outlineDecorative: colors.neutral20,
    outlineContainer: colors.neutral05,
    outlineInputEnabled: colors.neutral40,
    outlineInputHover: colors.neutral60,
    outlineInputFocus: colors.interactive40,
    outlineInputDisabled: colors.neutral40_30,
    outlineInformative: colors.informative30,
    outlinePositive: colors.positive50,
    outlineWarning: colors.warning40,
    outlineNegative: colors.negative30,
  },
  dataVisualizationColor: {
    pastelGrey: colors.neutral01,
    pastelRed: colors.red01,
    pastelOrange: colors.orange01,
    pastelYellow: colors.yellow01,
    pastelGreen: colors.green01,
    pastelJade: colors.jade01,
    pastelBlue: colors.blue01,
    pastelIndigo: colors.indigo01,
    pastelViolet: colors.violet01,
    pastelPink: colors.pink01,
    softGrey: colors.neutral10,
    softRed: colors.red10,
    softOrange: colors.orange10,
    softYellow: colors.yellow10,
    softGreen: colors.green10,
    softJade: colors.jade10,
    softBlue: colors.blue10,
    softIndigo: colors.indigo10,
    softViolet: colors.violet10,
    softPink: colors.pink10,
    brightGrey: colors.neutral30,
    brightRed: colors.red30,
    brightOrange: colors.orange30,
    brightYellow: colors.yellow30,
    brightGreen: colors.green30,
    brightJade: colors.jade30,
    brightBlue: colors.blue30,
    brightIndigo: colors.indigo30,
    brightViolet: colors.violet30,
    brightPink: colors.pink30,
    darkGrey: colors.neutral50,
    darkRed: colors.red50,
    darkOrange: colors.orange50,
    darkYellow: colors.yellow50,
    darkGreen: colors.green50,
    darkJade: colors.jade50,
    darkBlue: colors.blue50,
    darkIndigo: colors.indigo50,
    darkViolet: colors.violet50,
    darkPink: colors.pink50,
  },
  elevations: {
    elevationSmall: `0px 4px 8px ${colors.black_16}`,
    elevationMedium: `0px 8px 16px ${colors.black_16}`,
    elevationLarge: `0px 16px 32px ${colors.black_16}`,
  },
};
