function p(){p=Object.assign||function(a){for(var d=1;d<arguments.length;d++){var e=arguments[d],l;for(l in e)Object.prototype.hasOwnProperty.call(e,l)&&(a[l]=e[l])}return a};return p.apply(this,arguments)}var v,x=v||(v={});x.Pop="POP";x.Push="PUSH";x.Replace="REPLACE";var y="production"!==process.env.NODE_ENV?function(a){return Object.freeze(a)}:function(a){return a};function z(a,d){if(!a){"undefined"!==typeof console&&console.warn(d);try{throw Error(d);}catch(e){}}}
function C(a){a.preventDefault();a.returnValue=""}function D(){var a=[];return{get length(){return a.length},push:function(d){a.push(d);return function(){a=a.filter(function(e){return e!==d})}},call:function(d){a.forEach(function(e){return e&&e(d)})}}}function E(a){var d=a.pathname,e=a.search;a=a.hash;return(void 0===d?"/":d)+(void 0===e?"":e)+(void 0===a?"":a)}
function F(a){var d={};if(a){var e=a.indexOf("#");0<=e&&(d.hash=a.substr(e),a=a.substr(0,e));e=a.indexOf("?");0<=e&&(d.search=a.substr(e),a=a.substr(0,e));a&&(d.pathname=a)}return d}
var K=function(a){function d(){var b=F(m.location.hash.substr(1)),c=b.pathname,g=b.search;b=b.hash;var h=q.state||{};return[h.idx,y({pathname:void 0===c?"/":c,search:void 0===g?"":g,hash:void 0===b?"":b,state:h.usr||null,key:h.key||"default"})]}function e(){if(w)k.call(w),w=null;else{var b=v.Pop,c=d(),g=c[0];c=c[1];if(k.length)if(null!=g){var h=n-g;h&&(w={action:b,location:c,retry:function(){r(-1*h)}},r(h))}else"production"!==process.env.NODE_ENV?z(!1,"You are trying to block a POP navigation to a location that was not created by the history library. The block will fail silently in production, but in general you should do all navigation with the history library (instead of using window.history.pushState directly) to avoid this situation."):
void 0;else A(b)}}function l(b){var c=document.querySelector("base"),g="";c&&c.getAttribute("href")&&(c=m.location.href,g=c.indexOf("#"),g=-1===g?c:c.slice(0,g));return g+"#"+("string"===typeof b?b:E(b))}function G(b,c){void 0===c&&(c=null);return y(p({pathname:t.pathname,hash:"",search:""},"string"===typeof b?F(b):b,{state:c,key:Math.random().toString(36).substr(2,8)}))}function A(b){B=b;b=d();n=b[0];t=b[1];H.call({action:B,location:t})}function I(b,c){function g(){I(b,c)}var h=v.Push,f=G(b,c);"production"!==
process.env.NODE_ENV?z("/"===f.pathname.charAt(0),"Relative pathnames are not supported in hash history.push("+JSON.stringify(b)+")"):void 0;if(!k.length||(k.call({action:h,location:f,retry:g}),!1)){var u=[{usr:f.state,key:f.key,idx:n+1},l(f)];f=u[0];u=u[1];try{q.pushState(f,"",u)}catch(L){m.location.assign(u)}A(h)}}function J(b,c){function g(){J(b,c)}var h=v.Replace,f=G(b,c);"production"!==process.env.NODE_ENV?z("/"===f.pathname.charAt(0),"Relative pathnames are not supported in hash history.replace("+
JSON.stringify(b)+")"):void 0;k.length&&(k.call({action:h,location:f,retry:g}),1)||(f=[{usr:f.state,key:f.key,idx:n},l(f)],q.replaceState(f[0],"",f[1]),A(h))}function r(b){q.go(b)}void 0===a&&(a={});a=a.window;var m=void 0===a?document.defaultView:a,q=m.history,w=null;m.addEventListener("popstate",e);m.addEventListener("hashchange",function(){var b=d()[1];E(b)!==E(t)&&e()});var B=v.Pop;a=d();var n=a[0],t=a[1],H=D(),k=D();null==n&&(n=0,q.replaceState(p({},q.state,{idx:n}),""));return{get action(){return B},
get location(){return t},createHref:l,push:I,replace:J,go:r,back:function(){r(-1)},forward:function(){r(1)},listen:function(b){return H.push(b)},block:function(b){var c=k.push(b);1===k.length&&m.addEventListener("beforeunload",C);return function(){c();k.length||m.removeEventListener("beforeunload",C)}}}}();export default K
//# sourceMappingURL=hash.js.map
