import { createGlobalThemeContract } from "@vanilla-extract/css";

export const vars = createGlobalThemeContract(
  {
    typography: {
      body: {
        fontFamily: null,
        fontWeight: { regular: null, strong: null },
        sizes: {
          small: {
            fontSize: null,
            lineHeight: null,
          },
          medium: {
            fontSize: null,
            lineHeight: null,
          },
          large: {
            fontSize: null,
            lineHeight: null,
          },
        },
      },
      display: {
        fontFamily: null,
        fontWeight: null,
        sizes: {
          small: {
            fontSize: null,
            lineHeight: null,
          },
          medium: {
            fontSize: null,
            lineHeight: null,
          },
          large: {
            fontSize: null,
            lineHeight: null,
          },
        },
      },
      headline: {
        fontFamily: null,
        fontWeight: null,
        sizes: {
          small: {
            fontSize: null,
            lineHeight: null,
          },
          medium: {
            fontSize: null,
            lineHeight: null,
          },
          large: {
            fontSize: null,
            lineHeight: null,
          },
        },
      },
      label: {
        fontFamily: null,
        fontWeight: null,
        sizes: {
          small: {
            fontSize: null,
            lineHeight: null,
          },
          medium: {
            fontSize: null,
            lineHeight: null,
          },
          large: {
            fontSize: null,
            lineHeight: null,
          },
        },
      },
      title: {
        fontFamily: null,
        fontWeight: null,
        sizes: {
          small: {
            fontSize: null,
            lineHeight: null,
          },
          medium: {
            fontSize: null,
            lineHeight: null,
          },
          large: {
            fontSize: null,
            lineHeight: null,
          },
        },
      },
    },
    brandColor: {
      brandPrimary: null,
      brandSecondary: null,
      brandTertiary: null,
    },
    backgroundColor: {
      backgroundPrimary: null,
      backgroundSecondary: null,
      backgroundOverlay: null,
      backgroundPrimaryInverse: null,
      backgroundSecondaryInverse: null,
      backgroundInteractive: null,
      backgroundInteractiveOverlay: null,
      backgroundInformative: null,
      backgroundPositive: null,
      backgroundWarning: null,
      backgroundNegative: null,
      backgroundLightScrim: null,
      backgroundDarkScrim: null,
    },
    foregroundColor: {
      foregroundPrimary: null,
      foregroundSecondary: null,
      foregroundPrimaryInverse: null,
      foregroundSecondaryInverse: null,
      foregroundInteractive: null,
      foregroundInformative: null,
      foregroundPositive: null,
      foregroundWarning: null,
      foregroundNegative: null,
      foregroundDisabled: null,
    },
    textColor: {
      textPrimary: null,
      textSecondary: null,
      textPrimaryInverse: null,
      textSecondaryInverse: null,
      textInteractive: null,
      textInformative: null,
      textPositive: null,
      textWarning: null,
      textNegative: null,
      textDisabled: null,
    },
    interactiveBackgroundColor: {
      primarySolidEnabledBackground: null,
      primarySolidHoverBackground: null,
      primarySolidFocusBackground: null,
      primaryTransparentEnabledBackground: null,
      primaryTransparentHoverBackground: null,
      primaryTransparentFocusBackground: null,
      secondarySolidEnabledBackground: null,
      secondarySolidHoverBackground: null,
      secondarySolidFocusBackground: null,
      secondaryTransparentEnabledBackground: null,
      secondaryTransparentHoverBackground: null,
      secondaryTransparentFocusBackground: null,
      dangerSolidEnabledBackground: null,
      dangerSolidHoverBackground: null,
      dangerSolidFocusBackground: null,
      dangerTransparentEnabledBackground: null,
      dangerTransparentHoverBackground: null,
      dangerTransparentFocusBackground: null,
      disabledSolidBackground: null,
      disabledTransparentBackground: null,
    },
    interactiveForegroundColor: {
      primarySolidEnabledForeground: null,
      primarySolidHoverForeground: null,
      primarySolidFocusForeground: null,
      primaryTransparentEnabledForeground: null,
      primaryTransparentHoverForeground: null,
      primaryTransparentFocusForeground: null,
      secondarySolidEnabledForeground: null,
      secondarySolidHoverForeground: null,
      secondarySolidFocusForeground: null,
      secondaryTransparentEnabledForeground: null,
      secondaryTransparentHoverForeground: null,
      secondaryTransparentFocusForeground: null,
      dangerSolidEnabledForeground: null,
      dangerSolidHoverForeground: null,
      dangerSolidFocusForeground: null,
      dangerTransparentEnabledForeground: null,
      dangerTransparentHoverForeground: null,
      dangerTransparentFocusForeground: null,
      disabledSolidForeground: null,
      disabledTransparentForeground: null,
      linkEnabled: null,
      linkHover: null,
      linkFocus: null,
      linkDisabled: null,
      linkEnabledInverse: null,
      linkHoverInverse: null,
      linkFocusInverse: null,
      linkDisabledInverse: null,
    },
    outlineColor: {
      outlineInteractive: null,
      outlineInteractivePrimaryEnabled: null,
      outlineInteractivePrimaryFocus: null,
      outlineInteractivePrimaryHover: null,
      outlineInteractiveSecondaryEnabled: null,
      outlineInteractiveSecondaryFocus: null,
      outlineInteractiveSecondaryHover: null,
      outlineInteractiveDangerEnabled: null,
      outlineInteractiveDangerFocus: null,
      outlineInteractiveDangerHover: null,
      outlineInteractiveDisabled: null,
      outlineDecorative: null,
      outlineContainer: null,
      outlineInputEnabled: null,
      outlineInputHover: null,
      outlineInputFocus: null,
      outlineInputDisabled: null,
      outlineInformative: null,
      outlinePositive: null,
      outlineWarning: null,
      outlineNegative: null,
    },
    dataVisualizationColor: {
      pastelGrey: null,
      pastelRed: null,
      pastelOrange: null,
      pastelYellow: null,
      pastelGreen: null,
      pastelJade: null,
      pastelBlue: null,
      pastelIndigo: null,
      pastelViolet: null,
      pastelPink: null,
      softGrey: null,
      softRed: null,
      softOrange: null,
      softYellow: null,
      softGreen: null,
      softJade: null,
      softBlue: null,
      softIndigo: null,
      softViolet: null,
      softPink: null,
      brightGrey: null,
      brightRed: null,
      brightOrange: null,
      brightYellow: null,
      brightGreen: null,
      brightJade: null,
      brightBlue: null,
      brightIndigo: null,
      brightViolet: null,
      brightPink: null,
      darkGrey: null,
      darkRed: null,
      darkOrange: null,
      darkYellow: null,
      darkGreen: null,
      darkJade: null,
      darkBlue: null,
      darkIndigo: null,
      darkViolet: null,
      darkPink: null,
    },
    elevations: {
      elevationSmall: null,
      elevationMedium: null,
      elevationLarge: null,
    },
  },
  (_value, path) => `bento-${path.join("-")}`
);
