#!/usr/bin/env node
"use strict";

var _chunk7GS53OSVjs = require('./chunk-7GS53OSV.js');


var _chunkN7E4SOWGjs = require('./chunk-N7E4SOWG.js');


var _chunkXB3EXQUVjs = require('./chunk-XB3EXQUV.js');

// src/cli-default.ts
_chunkXB3EXQUVjs.init_cjs_shims.call(void 0, );
_chunk7GS53OSVjs.main.call(void 0, ).catch(_chunkN7E4SOWGjs.handleError);
