import { createThemeContract } from "@vanilla-extract/css";

export const vars = createThemeContract({
  fontFamily: {
    default: null,
  },
  fontWeight: {
    regular: null,
    semibold: null,
  },
  fontSize: {
    bodySmall: null,
    bodyMedium: null,
    bodyLarge: null,
    displaySmall: null,
    displayMedium: null,
    displayLarge: null,
    headlineSmall: null,
    headlineMedium: null,
    headlineLarge: null,
    labelSmall: null,
    labelMedium: null,
    labelLarge: null,
    titleSmall: null,
    titleMedium: null,
    titleLarge: null,
  },
  lineHeight: {
    bodySmall: null,
    bodyMedium: null,
    bodyLarge: null,
    displaySmall: null,
    displayMedium: null,
    displayLarge: null,
    headlineSmall: null,
    headlineMedium: null,
    headlineLarge: null,
    labelSmall: null,
    labelMedium: null,
    labelLarge: null,
    titleSmall: null,
    titleMedium: null,
    titleLarge: null,
  },
  letterSpacing: {
    1: null,
    2: null,
  },
  space: {
    0: null,
    4: null,
    8: null,
    16: null,
    24: null,
    32: null,
    40: null,
    80: null,
  },
  radius: {
    4: null,
    8: null,
    16: null,
  },
  brandColor: {
    brandPrimary: null,
    brandSecondary: null,
    brandTertiary: null,
  },
  backgroundColor: {
    backgroundPrimary: null,
    backgroundSecondary: null,
    backgroundInformative: null,
    backgroundPositive: null,
    backgroundWarning: null,
    backgroundNegative: null,
    backgroundLightOverlay: null,
    backgroundDarkOverlay: null,
  },
  foregroundColor: {
    foregroundPrimary: null,
    foregroundSecondary: null,
    foregroundInformative: null,
    foregroundPositive: null,
    foregroundWarning: null,
    foregroundNegative: null,
    foregroundDisabled: null,
  },
  textColor: {
    textPrimary: null,
    textSecondary: null,
    textInformative: null,
    textPositive: null,
    textWarning: null,
    textNegative: null,
    textDisabled: null,
  },
  interactiveBackgroundColor: {
    solidEnabledBackground: null,
    solidHoverBackground: null,
    solidFocusBackground: null,
    solidActiveBackground: null,
    solidDisabledBackground: null,
    transparentEnabledBackground: null,
    transparentHoverBackground: null,
    transparentFocusBackground: null,
    transparentActiveBackground: null,
    transparentDisabledBackground: null,
    dangerEnabledBackground: null,
    dangerHoverBackground: null,
    dangerFocusBackground: null,
    dangerDisabledBackground: null,
  },
  interactiveForegroundColor: {
    solidEnabledForeground: null,
    solidHoverForeground: null,
    solidFocusForeground: null,
    solidActiveForeground: null,
    solidDisabledForeground: null,
    transparentEnabledForeground: null,
    transparentHoverForeground: null,
    transparentFocusForeground: null,
    transparentActiveForeground: null,
    transparentDisabledForeground: null,
    dangerEnabledForeground: null,
    dangerHoverForeground: null,
    dangerFocusForeground: null,
    dangerDisabledForeground: null,
  },
  outlineColor: {
    outlineInput: null,
    outlineInteractive: null,
    outlineDecorative: null,
    outlineContainer: null,
    outlineNegative: null,
    outlineDisabled: null,
  },
  dataVisualizationColor: {
    softGrey: null,
    softRed: null,
    softOrange: null,
    softYellow: null,
    softGreen: null,
    softJade: null,
    softBlue: null,
    softIndigo: null,
    softViolet: null,
    softPink: null,
    brightGrey: null,
    brightRed: null,
    brightOrange: null,
    brightYellow: null,
    brightGreen: null,
    brightJade: null,
    brightBlue: null,
    brightIndigo: null,
    brightViolet: null,
    brightPink: null,
  },
  boxShadow: {
    outlineInput: null,
    outlineInteractive: null,
    outlineInteractiveStrong: null,
    outlineNegative: null,
    outlineNegativeStrong: null,
    outlineDisabled: null,
    elevationSmall: null,
    elevationMedium: null,
    elevationLarge: null,
  },
  zIndex: {
    modalUnderlay: null,
  },
});
