import { createGlobalTheme, createTheme } from "@vanilla-extract/css";
import { vars as bentoVars } from "../src/vars.css";

const remBaseSize = 16;
const pixelToRem = (px: number) => `${px / remBaseSize}rem`;

const colors = {
  white: "#FFFFFF",
  black: "#000000",
  brandTertiary50: "#45C1C0",
  neutral01: "#F6F8FB",
  neutral05: "#ECEFF4",
  neutral20: "#CBD4E1",
  neutral40: "#9AA8BC",
  neutral50: "#728197",
  neutral60: "#525E6F",
  neutral70: "#3B4554",
  neutral80: "#27313F",
  neutral90: "#1A212B",
  informative05: "#D8E8FF",
  informative40: "#2D7AE5",
  informative60: "#004AB1",
  informative70: "#003B8D",
  positive05: "#DAFCE6",
  positive50: "#21C357",
  positive70: "#078631",
  warning05: "#FFF2D2",
  warning40: "#F2A60D",
  warning70: "#946300",
  negative05: "#FFD4D8",
  negative40: "#CE0718",
  negative50: "#CE0718",
  negative60: "#B1000F",
  negative70: "#8D000C",
  interactive80: "#333333",
};

const commonTheme = {
  fontFamily: {
    default: "Arial",
  },
  fontSize: {
    bodySmall: pixelToRem(12),
    bodyMedium: pixelToRem(14),
    bodyLarge: pixelToRem(16),
    headlineSmall: pixelToRem(24),
    headlineMedium: pixelToRem(28),
    headlineLarge: pixelToRem(32),
    displaySmall: pixelToRem(36),
    displayMedium: pixelToRem(45),
    displayLarge: pixelToRem(57),
    labelSmall: pixelToRem(11),
    labelMedium: pixelToRem(12),
    labelLarge: pixelToRem(14),
    titleSmall: pixelToRem(14),
    titleMedium: pixelToRem(16),
    titleLarge: pixelToRem(22),
  },
  lineHeight: {
    bodySmall: pixelToRem(16),
    bodyMedium: pixelToRem(18),
    bodyLarge: pixelToRem(20),
    headlineSmall: pixelToRem(30),
    headlineMedium: pixelToRem(36),
    headlineLarge: pixelToRem(40),
    displaySmall: pixelToRem(46),
    displayMedium: pixelToRem(56),
    displayLarge: pixelToRem(72),
    labelSmall: pixelToRem(14),
    labelMedium: pixelToRem(16),
    labelLarge: pixelToRem(18),
    titleSmall: pixelToRem(18),
    titleMedium: pixelToRem(20),
    titleLarge: pixelToRem(28),
  },
  fontWeight: {
    regular: "400",
    semibold: "600",
  },
  letterSpacing: {
    "1": "0.01em",
    "2": "0.02em",
  },
  space: {
    "0": "0",
    "4": "4px",
    "8": "8px",
    "16": "16px",
    "24": "24px",
    "32": "32px",
    "40": "40px",
    "80": "80px",
  },
  radius: {
    "4": "4px",
    "8": "8px",
    "16": "16px",
  },
  boxShadow: {
    primary: `inset 0px 0px 0px 1px ${colors.brandTertiary50}`,
    primaryStrong: `inset 0px 0px 0px 2px ${colors.brandTertiary50}`,
    neutral: `inset 0px 0px 0px 1px ${colors.neutral60}`,
    disabled: `inset 0px 0px 0px 1px ${colors.neutral40}`,
    negative: `inset 0px 0px 0px 1px ${colors.negative60}`,
    negativeStrong: `inset 0px 0px 0px 2px ${colors.negative60}`,
    dividerBottom: `inset 0px -1px 0px ${colors.neutral20}`,
    elevation4: `0px 4px 8px rgba(0, 0, 0, 0.16)`,
    elevation8: `0px 8px 16px rgba(0, 0, 0, 0.16)`,
    elevation16: `0px 16px 32px rgba(0, 0, 0, 0.16)`,
  },
};

export const lightTheme = createTheme(bentoVars, {
  ...commonTheme,
  semanticColor: {
    informative: colors.informative40,
    positive: colors.positive50,
    warning: colors.warning40,
    negative: colors.negative40,
  },
  textColor: {
    textPrimary: colors.neutral90,
    textSecondary: colors.neutral60,
    textInformative: colors.informative60,
    textPositive: colors.positive70,
    textWarning: colors.warning70,
    textNegative: colors.negative60,
    textDisabled: colors.neutral20,
  },
  interactiveColor: {
    interactivePrimaryEnabled: colors.black,
    interactivePrimaryHover: colors.interactive80,
    interactivePrimaryFocus: colors.interactive80,
    interactiveDangerEnabled: colors.negative40,
    interactiveDangerHover: colors.negative50,
    interactiveDangerFocus: colors.negative50,
    interactiveDisabled: colors.neutral05,
  },
  onInteractiveColor: {
    interactivePrimaryOnEnabled: colors.white,
    interactivePrimaryOnHover: colors.white,
    interactivePrimaryOnFocus: colors.white,
    interactiveDangerOnEnabled: colors.white,
    interactiveDangerOnHover: colors.white,
    interactiveDangerOnFocus: colors.white,
    interactiveOnDisabled: colors.neutral20,
  },
  backgroundColor: {
    backgroundPrimary: colors.white,
    backgroundSecondary: colors.neutral01,
    backgroundInformative: colors.informative05,
    backgroundPositive: colors.positive05,
    backgroundWarning: colors.warning05,
    backgroundNegative: colors.negative05,
    backgroundDisabled: colors.neutral05,
  },
  outlineColor: {
    interactive: colors.black,
    input: colors.neutral60,
    decorative: colors.neutral20,
    container: colors.neutral05,
    error: colors.negative40,
    disabled: colors.neutral20,
  },
});

export const darkTheme = createTheme(bentoVars, {
  ...commonTheme,
  semanticColor: {
    informative: colors.informative40,
    positive: colors.positive50,
    warning: colors.warning40,
    negative: colors.negative40,
  },
  textColor: {
    textPrimary: colors.white,
    textSecondary: colors.neutral40,
    textInformative: colors.white,
    textPositive: colors.white,
    textWarning: colors.white,
    textNegative: colors.white,
    textDisabled: colors.neutral50,
  },
  interactiveColor: {
    interactivePrimaryEnabled: colors.white,
    interactivePrimaryHover: colors.white,
    interactivePrimaryFocus: colors.white,
    interactiveDangerEnabled: colors.negative40,
    interactiveDangerHover: colors.negative50,
    interactiveDangerFocus: colors.negative50,
    interactiveDisabled: colors.neutral70,
  },
  onInteractiveColor: {
    interactivePrimaryOnEnabled: colors.black,
    interactivePrimaryOnHover: colors.black,
    interactivePrimaryOnFocus: colors.black,
    interactiveDangerOnEnabled: colors.white,
    interactiveDangerOnHover: colors.white,
    interactiveDangerOnFocus: colors.white,
    interactiveOnDisabled: colors.neutral50,
  },
  backgroundColor: {
    backgroundPrimary: colors.neutral90,
    backgroundSecondary: colors.neutral80,
    backgroundInformative: colors.informative70,
    backgroundPositive: colors.positive70,
    backgroundWarning: colors.warning70,
    backgroundNegative: colors.negative70,
    backgroundDisabled: colors.neutral70,
  },
  outlineColor: {
    interactive: colors.black,
    input: colors.neutral60,
    decorative: colors.neutral20,
    container: colors.neutral05,
    error: colors.negative40,
    disabled: colors.neutral20,
  },
});

export const vars = createGlobalTheme(":root", {
  fontFamily: {
    customFontFamily: "sans-serif",
  },
  color: {
    customColor1: "#3C6FD6",
  },
  space: {
    "12": "12px",
  },
});
